---
- name: ipa
  become: true
  hosts: ipa.otus.lan
  
  tasks:
          - name: time
            command: timedatectl set-timezone Europe/Moscow
            tags: time
          - name: chronyd install
            yum:
                    name:
                            - chrony
                    state: latest
            tags: chronyd install
          - name: chrony start and enable
            service:
                    name: chronyd
                    state: started
                    enabled: true
            tags: chrony start and enable
          - name: ipa-firewalld
            service:
                    name: firewalld
                    state: started
                    enabled: true
            tags: start firewalld
          - name: settings firewalld
            shell:
                    cmd: 'firewall-cmd --zone=public --add-service=freeipa-ldap --add-service=freeipa-ldaps --permanent'
            tags: settings firewalld
          - name: restart firewalld
            command: systemctl restart firewalld
            tags: restart firewalld
          - name: selinux ipa
            command: setenforce 0
            tags: selinux ipa
          - name: hosts ipa
            shell:
                    cmd: 'echo -e "127.0.0.1   localhost localhost.localdomain \n127.0.1.1 ipa.otus.lan ipa \n192.168.57.10 ipa.otus.lan ipa" >> /etc/hosts'
            tags: hosts ipa
          - name: ipa-server install
            yum:
                    name: ipa-server
                    state: latest
            tags: ipa-server install
  tags: servers

- name: clients
  become: true
  hosts: clients
  tasks:
          - name: soft clients
            yum:
                    name:
                            - vim
                            - chrony
                    state: present
                    update_cache: true
            tags: soft clients
          - name: firewall clients
            service:
                    name: firewalld
                    state: stopped
                    enabled: false
            tags: firewall clients
          - name: selinux clients
            selinux:
                    state: disabled
            tags: selinux clients
          - name: disbaled selinux clients
            shell: setenforce 0
            tags: disbaled selinux clients
          - name: chrony clients
            service:
                    name: chronyd
                    state: restarted
                    enabled: true
            tags:  chrony clients
          - name: hosts clients
            shell:
                    cmd: 'echo -e "192.168.57.10 ipa.otus.lan ipa" >> /etc/hosts'
            tags: hosts clients
          - name: install module ipa-client
            yum:
                    name:
                            -  freeipa-client
                    state: present
                    update_cache: true
            tags: install module ipa-client
          - name: add host to ipa-server
            shell: 'echo -e "yes\nyes" | ipa-client-install --mkhomedir --domain=OTUS.LAN --server=ipa.otus.lan --no-ntp -p admin -w Otus2023'
            tags: install module ipa-client
  tags: clients
