---
- name: tap for all
  become: true
  hosts: all

  tasks:
          - name: install epel-release
            yum:
                    name:
                            - epel-release
                    state: latest
            tags: epel

          - name: install soft
            yum:
                    name:
                            - openvpn
                            - iperf3
            tags: soft
          - name: selinux off
            command: setenforce 0
            tags: selinux off
  tags: tap for all

- name: tap for server
  become: true
  hosts: server

  tasks:
          - name: generate secret
            command: openvpn --genkey --secret /etc/openvpn/static.key
            tags: generate secret

          - name: copy server.conf
            copy:
                    src: /home/dima/iptables_lab/server/server.conf
                    dest: /etc/openvpn
            loop:
                    - server.conf
            tags: copy server.conf
          - name: copy openvpv@.service
            become: true
            copy:
                    src:  /home/dima/iptables_lab/server/openvpn@.service
                    dest: /etc/systemd/system/openvpn@.service
            tags: copy openvpn@.service
          - name: start openvpn@server on server
            command: systemctl start openvpn@server
            tags: start openvpn@server on server
          - name: enable openvpn@server on server
            command: systemctl enable openvpn@server
            tags: enable openvpn@server on server
          - name: copy static.key on host
            fetch:
                    src: /etc/openvpn/static.key
                    dest: /home/dima/iptables_lab/client/static.key
            tags: copy static.key on host
  tags: settings server

- name: settings client
  become: true
  hosts: client

  tasks: 
         - name: copy server.conf on client
           copy:
                   src: /home/dima/iptables_lab/client/server.conf
                   dest: /etc/openvpn/server.conf
           tags: copy server.conf on client
         - name: copy statyc.key on client
           copy:
                   src: /home/dima/iptables_lab/client/static.key
                   dest: /etc/openvpn/static.key
           tags: copy static.key on client
         - name: start openvpn@server on client
           command: systemctl start openvpn@server
           tags: start openvpn@server on client
         - name: enable openvpn@server on client
           command: systemctl enable openvpn@server
           tags: enable openvpn@server on client
  tags: settings client





