---
- name: "install pxeserver"
hosts: pxeserver
become: true
vars_files:
    - defaults/main.yml

tasks:
- name: 
set up repo
    replace:
      path: "{{ item }}"
      regexp: 'mirrorlist'
      replace: '#mirrorlist'
    with_items:
      - /etc/yum.repos.d/CentOS-Linux-AppStream.repo
      - /etc/yum.repos.d/CentOS-Linux-BaseOS.repo
tags:
     - setuprepo

- name: set up repo
    replace:
      path: "{{ item }}"
      regexp: '#baseurl=http://mirror.centos.org'
      replace: 'baseurl=http://vault.centos.org'
    with_items:
      - /etc/yum.repos.d/CentOS-Linux-AppStream.repo
      - /etc/yum.repos.d/CentOS-Linux-BaseOS.repo
tags: 
      - setuprepo2

      - name: install softs on CentOS
    yum:
      name:
        - vim
        - wget
        - epel-release
        - httpd
        - tftp-server
        - dhcp-server
      state: present
      update_cache: true
      tags: 
      - soft

       - name: Download ISO image CentOS 8.4.2105
    get_url:
      url: https://mirror.sale-dedic.com/centos/8.4.2105/isos/x86_64/CentOS-8.4.2105-x86_64-dvd1.iso
      dest: ~/CentOS-8.4.2105-x86_64-dvd1.iso
      mode: '0755'
      tags: 
       - download

       - name: Create ISO directory
    file:
      path: /iso
      state: directory
      mode: '0755'
      tags: 
      - create

      - name: Mount ISO image
    mount:
      path: /mnt
      src: /root/CentOS-8.4.2105-x86_64-dvd1.iso
      fstype: iso9660
      opts: ro,loop
      state: mounted
      tags:
      - mount

      - name: copy ALL files from /mnt to /iso
    copy:
      src: /mnt/
      dest: /iso
      remote_src: yes 
      directory_mode: yes
      tags: 
      - copy

      - name: set up httpd config
    template:
      src: pxeboot.conf
      dest: /etc/httpd/conf.d/pxeboot.conf 
      owner: root
      group: root
      mode: 0640
      tags:
      - httpd

        - name: restart httpd
    service:
      name: httpd
      state: restarted
      enabled: true
      tags:
      - httpdrestart

      - name: Create TFTP directory
    file:
      path: /var/lib/tftpboot/pxelinux.cfg
      state: directory
      mode: '0755'
      tags: 
      - tftpdir

      - name: set up pxelinux
    template:
      src: default
      dest: /var/lib/tftpboot/pxelinux.cfg/default
      owner: root
      group: root
      mode: 0644
      tags:
      - copytftp

        - name: extract packages syslinux
    shell: rpm2cpio /iso/BaseOS/Packages/syslinux-tftpboot-6.04-5.el8.noarch.rpm | cpio -dimv
    tags:
         - extract


           - name: copy files to TFTP share
    copy:
      src: /home/vagrant/tftpboot/{{ item }}
      dest: /var/lib/tftpboot/{{ item }}
      mode: '0644'
      remote_src: true
    with_items:
      - pxelinux.0
      - ldlinux.c32
      - libmenu.c32
      - libutil.c32
      - menu.c32
      - vesamenu.c32
    tags:
    - copytotftpshare

    - name: copy initrd and vmlinuz files to TFTP share
    copy:
      src: /iso/images/pxeboot/{{ item }}
      dest: /var/lib/tftpboot/{{ item }}
      mode: '0755'
      remote_src: true
    with_items:
      - initrd.img
      - vmlinuz
    tags: 
    - vmlinuz

      - name: restart tftp-server
    service:
      name: tftp.service
      state: restarted
      enabled: true
      tags:
      - restarttftp

      - name: set up dhcp-server
    template:
      src: dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      mode: '0644'
      tags:
      - installdhcp

        - name: restart dhcp-server
    service:
      name: dhcpd
      state: restarted
      enabled: true
      tags:
      - restartdhcp

      
